import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import helmet from '@fastify/helmet';
import cors from '@fastify/cors';
import fastifyCsrf from '@fastify/csrf-protection';
import { AppModule } from './modules';

import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { ValidationPipe } from '@nestjs/common';

import metadata from './metadata'; // <-- file auto-generated by the "PluginMetadataGenerator"

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
  );
  app.useGlobalPipes(new ValidationPipe());

  //#region DOCUMENTATION
  const config = new DocumentBuilder()
    .setTitle('nestJS Template')
    .setDescription('API description')
    .setVersion('1.0')
    .build();

  await SwaggerModule.loadPluginMetadata(metadata);
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('docs', app, document);
  //#endregion

  //#region SECURITY

  await app.register(fastifyCsrf);
  await app.register(helmet);
  await app.register(cors, {
    origin: '*',
  });
  //#endregion

  await app.listen(8080);
}
bootstrap();
